### ISSUE TITLE
issue：How can I be as good as you

### ISSUE THREAD

**Issue by twototwotwo** [classmatewu/ToyWebpack#1]

**Comment by classmatewu** [comment]
Thanks, brother. You're so niubilitily, always be my example.

**Comment by twototwotwo** [comment]
No，you are always yyds，but I can‘t



发自我的iPhone 13 pro max


------------------ Original ------------------
From: Herry ***@***.***&gt;
Date: Sun,Oct 3,2021 0:59 PM
To: classmatewu/ToyWebpack ***@***.***&gt;
Cc: wsjiu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [classmatewu/ToyWebpack] issue：How can I be as good as you (#1)
